name: Keep Alive

on:
  workflow_dispatch:

  schedule:
    - cron: "*/20 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping
        run: |
          curl -k -L -s -o /dev/null -w "%{http_code}\n" https://6f7db3ufp7egvrin-free-app.stackhost.org
